= 闽东语拼音方案规范
:toc:
:toc-placement!:
:toc-title: 目录

方案版本: 0.4.0-preview1

修订时间: 2019 年 12 月 18 日

NOTE: 闽东语拼音方案尚初于初稿阶段，可能随时作出改动。笔者在此将拼音方案白皮书的初稿发布至网络，供小范围传阅及吸收批评意见。 
--子善

toc::[]

== 简介

闽东语拼音方案是用于表示... (待补充)

方案规范分为**主方案**（本文）和各地口音**分册**。

**主方案** 综述方案的设计理念，对符号的使用作出定义和规范，以及方案的版本控制等。

各地**分册**细化如何将闽东语拼音方案用于表示该地的口音，提供例子，以及对该地口音特殊的用法作出说明。

目前支持的口音包括：

* link:hukziu.adoc[福州市区 / 闽侯县 / 长乐区]
* 连江城关
* 闽清坂东 / 诗巫
* 古田城关 / 实兆远
* 福清城关

=== 设计原则

设计时综合考虑兼容福州十邑口音、初学者学习和在电子设备上输入的方便性。

(待补充)

== 符号定义

闽东语拼音方案定义了辅音、元音和声调符号。辅音和元音基于国际音标 (IPA) 的宽式写法。

=== 辅音符号
[options="header,footer,autowidth"]
|===
| 国际音标 | 闽东语拼音
| p     | b
| pʰ    | p
| m     | m
| t     | d
| tʰ    | t
| n     | n

| l 
.2+.^| l
| ɾ footnote:[/ɾ\]是声母d、t、l、s在阴声韵或入声h后类化产生的声母，与声母l不形成对立。按招学界描写闽东语连读系统的习惯，与之合并。] 

| s     | s
| θ     | th
| ʦ     | z
| ʦʰ    | c
| k     | g
| kʰ    | k
| ŋ     | ng

| h 
.2+.^| h
| ʔ footnote:[/ʔ\]是声门塞音韵尾，与声母h不形成对立。按照先前各类闽东语罗马字的书写习惯，与之合并。] 

| β     | w
| z     | j
| nz    | nj
| j     | i
| w     | u
|===


=== 元音符号
[options="header,footer,autowidth"]
|===
| 国际音标 | 闽东语拼音
| i    | i
| y    | y
| e    | e
| ø    | eo
| ɛ    | ee
| œ    | oe
| a    | a
| u    | u
| o    | o
| ɔ    | oo
|===

=== 声调符号

闽东语拼音方案中的声调可以使用数字标示法与五度标记法来标记。

在各地方案中，连读后的声调也有表示。

NOTE: 虽然闽东语拼音方案可以用来表示本字音和表层音(surface form, 即连读后的读音)。但方案中的声调符号，包括用五度标记法的表示，实际上只是对限定的调类的归类，而非对实际发音的精确描述。

声调名称与数字标示法的数字顺序以《戚林八音》中的名称与顺序为标准。

[options="header,footer,autowidth"]
|===
| 调类 | 上平 | 上上 | 上去 | 上入 | 下平 | 下上 footnote:[下上调无字。] | 下去 | 下入 | 轻声
| 数字 | 1    | 2    | 3    | 4    | 5    | -- | 7    | 8    | 0
| 例子 | a¹   | a²   | a³   | ah⁴  | a⁵   | -- | a⁷   | ah⁸  | a⁰
|===

== 详细使用规则
=== 辅音符号使用说明

1) 闽东语拼音方案在辅音符号的使用上，始终反映实际发音。若发生连读而引起声母类化，则需要表示出变化后的声母。但韵尾类化则不须表示。

在发生连读而塞音韵尾脱落时，可以视情况选择塞音韵尾符号的省略与否。譬如，实际教学中，为了强调变调的种类可以不省略已脱落的塞音韵尾。闽东语拼音方案默认不省略。

在发生连读而韵尾被后字声母类化时，可以视情况选择韵尾符号的改变与否。譬如，实际教学中，为了强调实际发音可以改变在连读中被后字同化的韵尾的符号。闽东语拼音方案默认不改变。

2) 声母th是声母s的变体，在二者没有对立的情况下（如福清），选择s表示[θ]。

3) 由于不存在对立，福安话的半元音声母[j]、[w]以元音i与u表示。

=== 元音符号使用说明

1) 闽东语拼音方案在元音符号的使用上，始终反映实际发音。若因为连读或在轻声条件下使松韵变为紧韵，则写出紧韵的实际发音。

2) 在没有声母的情况下，元音符号不作任何变形。不需要像普通话拼音一样，以yi、wu表示i、u。

3) 在韵母没有对立的情况下，选择舌面圆唇程度与前后位置相同，但开口较小的元音符号。这是为了达到拼写上的简洁，也是为了给松紧变韵后的韵母腾出符号选择的空间。如《戚林八音》歌韵写为o不写为oo，在简写拼音的同时给市区福州话歌韵的松韵腾出符号oo；又如《戚林八音》初韵写为eo不写为oe，在简写拼音的同时给福清话初韵的松韵腾出符号oe。

=== 声调符号的使用说明

1)	闽东语拼音方案在声调符号的使用上，默认不表示变调，而是以数字标示法标记字词中的单字原调。

在发生连读而引起变调时，可以视情况选择以五度标记法表示声调。譬如，实际教学中，为了强调变调的音值，可以不使用数字标示法而使用五度标记法。

2)	声调符号需要小写并上标于音节的右上角。如果条件不允许，在实际交流中不小写上标也可以。

3)	在实际交流中，若不产生歧义，不标记声调也可以。

=== 连字符使用说明
1) 在发生变调时，需要使用连字符“-”将发生变调的音节串联起来。

以连字符“-”串联的音节，需要按照上述三条使用说明，表示出声母的类化与韵母的松紧变韵，但不一定需要以五度标记法表示变调，以数字标示法表示原调即可。

在不发生变调但发生声母类化与变韵时，可以不使用连字符“-”串联音节。

=== 其他使用说明
1) 闽东语拼音方案是用来辅助学习闽东语发音与汉字写法的拼音，而不是一种表音文字。因此，闽东语拼音方案不使用标点符号，也没有大小写之分。若需要分隔音节，可以使用斜杠“/”。

== 使用例

==== 市区福州话

```
zing¹-njeu²-iang²/ doouk⁴ bo¹-wo¹
真鸟囝，啄菠菠。
sang¹-ngui³ hai⁵-i⁵ e⁷-cuong³-go¹
三岁孩儿会唱歌。
ing⁷-nei⁷ ba⁷-ne² ga³ nu⁵ cuong³
伓是罢嬭教奴唱，
si⁷-nu⁵ buk⁴-lo² teoyng¹-leoyng⁵-ngo¹
是奴腹老通珑哥。
```
（民谣《真鸟囝》节选）

==== 城关福清话

```
sang¹-zia³ zi²-muai³ pe⁵-pe⁵-iang⁵
三只姊妹排排行，
sing¹ seong⁷ eong⁵-ngo² kyo³ kang³-siang⁵
身颂红袄去看城。
lyong²-bieng¹ tu¹-le⁷ to⁵-li²-cieu³
两边都是桃李树，
oi³-sia¹ to⁵-li² neng⁷-ua¹-miang⁵
爱食桃李念花名。
```
（民谣《十二月花》节选）

==== 诗巫闽清话
```
gu⁷-le² u⁷-syoh⁸-lau⁵ dy¹-mo²
旧底有蜀头猪母，
i¹ yong² liu² sang¹-lau⁵ dy¹-iang²
伊养了三头猪囝。
i¹ zing⁷-tiang³ i¹ neong⁵
伊尽疼伊侬，
dang³-si⁷ mo⁵-noh⁴ do⁵ i¹ neong⁵ siah⁸
但是无乇掏伊侬食。
```
（童话《三只小猪》节选）

== 参考文献

(待补充)

* 福州及宁德所有的方言志
* 学界描写闽东语共时音系的论文及著作
* 官方出版的闽东语字词典
* 传教士留下的文献

== 规范管理

=== 名称规范

本方案中文名为 "闽东语拼音方案"，又名 "榕拼"。可在拉丁字母中写为 "YngPing"。用于计算机代码中时，亦可写作 "yngping"。

=== 版本控制

原则上遵循 语义化版本 https://semver.org/lang/zh-CN/

每次对方案文本的修订，都需要将版本号增加。同一时间只有一个版本号，**主方案**和各地**分册**始终是同一个版本号。版本号只写在**主方案**内。对各地**分册**的修改也需递增**主方案**内的版本号。

具体而言:

* 若对方案白皮书的修订不影响任何已有的使用和未来使用榕拼的文本，则只需修改修订号。
* 若对方案白皮书的修订不影响任何已有对文本，但新增了新的用法，则至少需递增次版本号。（如果修订变化很大，也可以递增主版本号）
* 若对方案白皮书的修订会影响现有的用法，则必须递增主版本号。


例如：

修改已有符号的含义或用法 => 主版本号

新增声母、韵母、声调符号，用于表示新的读音，而无需改动现有文本 => 次版本号。

方案文本字句修订、对现有用法的澄清、排版修改、段落排列顺序修改 => 修订号

=== 修订方式

修订通过 Github Pull Request 的方式进行。具体而言，将修改过的方案内容先提交到一个新的分支 (branch)，然后提出 Pull Request，将新分支合并到 master 分支。

每次修订需要写出修订内容摘要。

每次修订需要经过至少 2 人审阅（即修订提出者本人+另外一个人），才可合并到 master 分支。

== 之前的版本

在本方案白皮书规范化之前，已有的几个版本。各主要版本区别如下：

[options="header,autowidth"]
|===
| 版本 | 修订时间 | 修订内容摘要
| 0.1
| 2017 年
| 初版
| 0.2
| 2018 年 5 月
a|
*  去除 q 入声符号，改为区分 h、k 韵尾
*  新增手写方案
| 0.3
| 2019 年 9 月
a|
* 新增 oo 韵母，用于区分 ooung212，oung212 的对立。替换先前用 a 表示的“开口较大的 o”: aung242 -> ooung242, aung212 -> ooung212, auk23 -> oouk23。
|===
