# Just trying to build in order to ensure everything is not broken.
name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install mkdocs
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material pymdown-extensions
        mkdocs --version
    - name: Build
      run: mkdocs build
