name: 生成并部署网站

on: 
  push: 
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install mkdocs
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material pymdown-extensions
        mkdocs --version
    - name: Build
      run: mkdocs build
    - name: GitHub Pages Deploy | 部署
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: "site/"
        GH_PAT: ${{ secrets.GITHUB_TOKEN }}
